services:
  open-pulse-checker:
    build:
      context: .
      dockerfile: Dockerfile
    image: open-pulse-checker:local
    container_name: open-pulse-checker
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75
    restart: unless-stopped
